# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "ios-mysteries" do
	pod 'Liger', git: 'https://github.com/reachlocal/liger-ios'
end

target "ios-mysteriesTests" do

end

